### ISSUE TITLE
🐛 [BUG] - API Translation Refresh - Custom blocks settings

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#109]
### Description

Currently the API endpoint for refreshing translations extract all custom blocks settings (including secret). We need to restrict the translation refresh to only text like settings.

### Reproduction steps

```bash
1. Login and go to Visual Editor
2. Add the RAG custom block
3. Edit the block and go to "Message"
4. Update token
5. Go to "Localization / Translations"
6. Hit Refresh
7. You would be able to see the secret.
```

**Comment by kartik1112** [comment]
Hey @marrouchi can you assign this to me?

**Comment by marrouchi** [comment]
@kartik1112 Done 👍

**Comment by kartik1112** [comment]
![image](https://github.com/user-attachments/assets/e9926881-ddb5-4f4e-9efb-b58ffa91332a)

@marrouchi I can't see RAG custom block here.. Can you help?
and if i go for dummy I see empty space in messages tab

**Comment by marrouchi** [comment]
Hello @kartik1112, please do git pull latest from main and then install it : 
`npm install`
`npx hexabot install plugin Hexastack/hexabot-plugin-chatgpt`
It has been moved in a seperate repo and became installable. Sorry for the inconvinence.

**Comment by marrouchi** [comment]
@AuraOfDivinity Task has been assign to you since we didn't get any response from @kartik1112
