### ISSUE TITLE
🐛 [BUG] - Update of the content in the cms is getting failed

### ISSUE THREAD

**Issue by devamitranjan** [Hexastack/Hexabot#127]
### Description

When updating through toggle button or content dialog the status is not getting updated.
[problem.webm](https://github.com/user-attachments/assets/bd166f79-0f19-4713-8a0d-6f21cd240f5e)

### Reproduction steps

```bash
1. Go to 'Manage Content/CMS/Content Type'
2. Click on 'toggle button for the status in the listing page or inside modal'
3. Change the state.
4. See error
```

**Comment by devamitranjan** [comment]
@marrouchi Can you please assign this issue to me? I don't have access to assign it to myself.
Also, can you please add the hacktoberfest label if possible.

**Comment by marrouchi** [comment]
Hello @devamitranjan done !
