### ISSUE TITLE
🤔 [ISSUE] - Fix Typo in NLP Trainer

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#14]
### Description

![image](https://github.com/user-attachments/assets/1e300c88-7c74-43ad-9aba-98cb6caef0d5)
We should put "Type" instead of "Lookup Strategy" to indicate the type of dataset the sample should be in (Train or Test).

### Reproduction steps

```bash
1. Login
2. Go to 'NLP' in the left sidebar
```

**Comment by kartik1112** [comment]
On it 👍
