### ISSUE TITLE
🤔 [ISSUE] - Subscribers search input is too small

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#16]
### Description

![image](https://github.com/user-attachments/assets/caefd44f-1301-4e3e-97cb-91e1bb44ce30)

### Reproduction steps

```bash
1. Login
2. Click on 'Manage Subscribers > Subscribers'
```

**Comment by Advika101** [comment]
Hi I'd like to help. What exactly is the issue?

**Comment by medchedli** [comment]
Thank you @Advika101 


The current search input field on the subscribers management page is too small, making it difficult to enter longer search terms. Expand the width of the search input field to accommodate longer search queries. This will provide more space for users to enter terms without truncation or the need to scroll horizontally. Ensure the search input field remains usable and readable on different screen sizes (e.g., mobile, tablet, desktop) to maintain a consistent user experience.

**Comment by adititripathi** [comment]
@medchedli  I have tried fixing this issue please verify, if the issue has been resolved as expected do let me know if any problems are there. I have also attached a screen recording for confirmation.

**Comment by JaiSharma1710** [comment]
hi @marrouchi i have fixed this issue. please verify, and let me know in case of any problems
