### ISSUE TITLE
🤔 [ISSUE] - Add Error State and User Feedback to Block Input Fields

### ISSUE THREAD

**Issue by medchedli** [Hexastack/Hexabot#167]
### Description

Currently, the input fields of blocks do not have an error state. It is essential to implement error states for these input fields to improve user experience and provide clear feedback when there are validation errors.

#### Tasks
1. **Add Error State:**
   - Each input field should have an error state to indicate when the input is invalid.

2. **Use `helperText` Prop:**
   - Utilize the `helperText` prop to provide feedback to the user about the specific error.

3. **Example Implementation:**
   - In `PatternInput.tsx`, the `Input` component should include `error` and `helperText` props.

#### Files to Update
- [Input.tsx](https://github.com/Hexastack/Hexabot/blob/e11fb8b632fce0053b94c1f55a544129da891cb6/frontend/src/app-components/inputs/Input.tsx)
- Other relevant input components used within the blocks.

#### Acceptance Criteria
- All input fields in blocks should display an error state when the input is invalid.
- Validation needs to take place whenever the value of the input field changes.
- User should receive appropriate feedback via the `helperText` prop when there is an error.

### Reproduction steps

1. Navigate to the 'Visual Editor' page.
2. Add a new 'Simple Text' block.
3. Double-click on the 'Simple Text' block.
4. Enter an invalid Regex expression in the triggers tab. For example : '*'
5. Click 'Submit' to save the changes.
6. Observe that an alert notification pops up, but the input field itself does not display an error state.

![image](https://github.com/user-attachments/assets/ae59c81e-46eb-46b2-8a44-1d6ecf4563bb)

**Comment by PranavBhatP** [comment]
Hey! Can I take up this issue?

**Comment by medchedli** [comment]
Hi @PranavBhatP 

Sure. Thank you for your interest in Hexabot.

**Comment by PranavBhatP** [comment]
hey @medchedli , I've added error states for the Regex Input and the Text Input field under the Trigger category. Is there any other change/fix I must add, before creating a PR? Thanks.

**Comment by medchedli** [comment]
Thank you 👍@PranavBhatP 
 Please go ahead and create a PR. We will review it and provide feedback if any additional changes are needed.
