### ISSUE TITLE
🐛 [BUG] - Enabling Nginx doesn't work. 

### ISSUE THREAD

**Issue by MohamedAliBouhaouala** [Hexastack/Hexabot#219]
### Description

The command " npx hexabot dev --services nginx" doesn't work and throws an exception: undefined service "widget": invalid compose project.  

### Reproduction steps

```bash
1. Run the command "npx hexabot init" after installing all dependencies
2. Run the command "npx hexabot dev --services nginx"
3. See error
```

### Logs

```bash
service "nginx" depends on undefined service "widget": invalid compose project
Error executing Docker Compose command.
```

### OS

Linux

**Comment by teemuteekkari** [comment]
I'd like to work on this issue

**Comment by marrouchi** [comment]
Hello @teemuteekkari , thank you for taking this iniative. I just assigned the issue to you.

The fix should be easy, we should remove the widget vhost config from nginx and test.

**Comment by teemuteekkari** [comment]
Hey. This seemed pretty simple but currently I cannot seem to be able to run dev mode with --enable=nginx option as it keeps saying "unkwon option". I tried removing and uninstalling everything but still cannot seem to be working.

**Comment by marrouchi** [comment]
Hello @teemuteekkari , Sorry instead of "--enable=nginx" please use "--services nginx"

Also, can I ask where did you find in the documentation that it was mentioned to use "--enable=nginx" ?

**Comment by teemuteekkari** [comment]
Hi @marrouchi 
Couldn't find it in the documentation, the option is only mentioned on this issue

**Comment by marrouchi** [comment]
Yeah sorry about that, I will fix the description
