### ISSUE TITLE
🤔 [ISSUE] - Update Icons for Labels and Subscribers

### ISSUE THREAD

**Issue by Emnaghz** [Hexastack/Hexabot#43]
### Description

The current icons for labels and subscribers need to be updated for a more modern and consistent user interface. The new icons should align with the overall design and provide clearer representation for users.

![image](https://github.com/user-attachments/assets/a908e249-f133-4e2c-90bd-d118b018e42b)
![image](https://github.com/user-attachments/assets/5964cdc3-7567-4d83-b07a-d3f1feb44505)

### Reproduction steps

```bash
1. Go to Labels & Subscribers panels
```

**Comment by kartik1112** [comment]
Hey i've been working on this 

![image](https://github.com/user-attachments/assets/cd306915-9685-4798-b041-1586704df4e6)
![image](https://github.com/user-attachments/assets/f842f02e-a71b-4e1c-ac28-3146e9ff11a1)


are these okay or should I pick some icon from Font Awesome ? or if there are any other suggestions..

**Comment by JaiSharma1710** [comment]
hi @Emnaghz i have fixed the issue and created a pr for the same, please verify and let me know if something else is needed
