### ISSUE TITLE
🤔 [ISSUE] - Adjust success message on signup

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#44]
### Description

After a successful signup, a toast message shows "Changes saved". We need to display something like "Signup was successful, you will receive an email confirmation shortly." 

### Pre-requisites: 
- Read https://docs.hexabot.ai/developer-guide/smtp-configuration-and-emails
- This PR needs to be merged first, or you can branch our of it https://github.com/Hexastack/Hexabot/pull/42

### Reproduction steps

```bash
1. As an admin invite a user with an email
2. Open another browser or the private navigation to access the invite link
3. Fill the registration form
4. Check the toast message once you get redirected to the login page
```

**Comment by AuraOfDivinity** [comment]
I would like to work on this issue.

**Comment by marrouchi** [comment]
Yup please do, I will assign the issue to you.
