### ISSUE TITLE
🐛 [BUG] - Admin Console Widget - Solve UI Origins issues (CORS)

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#449]
### Description

When the user installs the latest version of Hexabot and runs the project, the admin console widget fails to connect because the allowed domains are misconfigured. Currently, the allowed domains are set to localhost instead of localhost:8080, which is the address of the Admin UI. The allowed domain should be set to localhost:8080 for the widget to function properly.

**Comment by medchedli** [comment]
#451
