### ISSUE TITLE
🤔 [ISSUE] - Improve Error Toast Messages to Provide Specific Feedback

### ISSUE THREAD

**Issue by Emnaghz** [Hexastack/Hexabot#45]
### Description

Currently, when an error occurs in the application (e.g., from backend validation), the error toast message only shows a generic message:
![image](https://github.com/user-attachments/assets/bc481fb7-c104-48ac-ae93-cac3238f0231)
This makes it difficult for the user to understand the specific issue and what action to take.

**Problem Cases:**

-  Creating a new category with an existing name: User doesn't know that the name must be unique.
-  Creating a new content type with an existing name: User isn't informed that a unique name is required.
-  Deleting a translation: No feedback explaining what went wrong or why the action couldn't be completed.
-  Creating a new role with an existing name: User doesn't receive information that the role name should be unique.

**Desired Behavior:**

Update the error toast messages to render specific errors based on the backend response, so the user understands what went wrong and can take appropriate action (e.g., "The name must be unique, please choose another name").

If it’s an internal server error, the existing generic toast message ("Oops! Something went wrong...") can still be shown.

Example Scenarios:

-  When a user attempts to create a category with a duplicate name, the toast should inform them:

   Message: "Category name already exists. Please choose a unique name."

-  When a user tries to delete a translation, and it fails for a specific reason, the toast should show a meaningful error.

-  For internal server errors, the generic error toast should still appear.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by kartik1112** [comment]
Hey.. Can you assign this to me ?

**Comment by PranavBhatP** [comment]
Hey, can I take up this issue?

**Comment by mSaurabh** [comment]
Can multiple people work on the same issue? @Emnaghz

**Comment by marrouchi** [comment]
@mSaurabh Do you want to work rather on this https://github.com/Hexastack/Hexabot/issues/114 ?
