### ISSUE TITLE
💡 [REQUEST] - Context vars : Permanent option

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#48]
### Summary

This is an important feature to implement, we need to add a flag for context variables called "permanent" boolean. Currently a context var value is only kept during the current conversation and then gets lost. It would be good to add the "permanent" option allow the value to be stored in the subscriber object in a attribute called "context" (json).

### Basic Example

- Add "permanent" attribute to the context var entity (boolean)
- Add "context" attribute in the subscriber entity (JSON object)

### Drawbacks

We cannot typecheck the user context object.

**Comment by medtaher123** [comment]
.
