### ISSUE TITLE
🤔 [ISSUE] - API Validation Pipe

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#79]
### Description

Payloads coming in over the network are plain JavaScript objects. The ValidationPipe can automatically transform payloads to be objects typed according to their DTO classes. To enable auto-transformation, set transform to true. 

```
app.useGlobalPipes(
  new ValidationPipe({
    transform: true,
  }),
);
```
### Reproduction steps

```bash
-
```

**Comment by devamitranjan** [comment]
https://github.com/Hexastack/Hexabot/pull/80
@marrouchi Added the changes

**Comment by marrouchi** [comment]
Thank you @devamitranjan  Can you please test all UI features to make sure it didn't break anything ?

**Comment by devamitranjan** [comment]
Sure @marrouchi will do.

**Comment by devamitranjan** [comment]
@marrouchi Looks good to me. It is working as before.
