### ISSUE TITLE
🤔 [ISSUE] - Add unit tests to the API translation service

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/Hexabot#87]
### Description

We need add unit tests to the API's TranslationService : api/src/i18n/services/translation.service.ts

### Reproduction steps

```bash
-
```

**Comment by mohitahlawat2001** [comment]
i want to work on this issue 
also want to know if i can use jest to write unit test?
please file where i have to write test cases

**Comment by yassinedorbozgithub** [comment]
> i want to work on this issue also want to know if i can use jest to write unit test? please file where i have to write test cases

Hi @mohitahlawat2001, yes you can use jest, we are already using jest for unit tests.
This is an unit test example file `api/src/user/services/auth.service.spec.ts`
If you want to find other files you can search **.spec.ts** suffix in the **api/**
